import 'package:equatable/equatable.dart';

/// Represents a vocabulary entry generated by AI
class VocabularyModel extends Equatable {
  final String id;
  final String word;
  final String partOfSpeech;
  final String thaiTranslation;
  final String englishSentence;
  final String thaiSentence;
  final String cefrLevel; // A1, A2, B1, B2
  final String communicativeFunction; // Indicative, Imperative, Subjunctive/Wish, Conditionals
  final String languageVariant; // US, UK
  final String imageUrl;
  final DateTime createdAt;
  final DateTime? updatedAt;
  final List<String> tags;
  final bool isFavorite;

  const VocabularyModel({
    required this.id,
    required this.word,
    required this.partOfSpeech,
    required this.thaiTranslation,
    required this.englishSentence,
    required this.thaiSentence,
    required this.cefrLevel,
    required this.communicativeFunction,
    required this.languageVariant,
    required this.imageUrl,
    required this.createdAt,
    this.updatedAt,
    this.tags = const [],
    this.isFavorite = false,
  });

  /// Create from AI-generated response
  factory VocabularyModel.fromAIResponse({
    required String word,
    required String partOfSpeech,
    required String thaiTranslation,
    required String englishSentence,
    required String thaiSentence,
    required String cefrLevel,
    required String communicativeFunction,
    required String languageVariant,
    required String imageUrl,
    List<String> tags = const [],
  }) {
    return VocabularyModel(
      id: _generateId(),
      word: word,
      partOfSpeech: partOfSpeech,
      thaiTranslation: thaiTranslation,
      englishSentence: englishSentence,
      thaiSentence: thaiSentence,
      cefrLevel: cefrLevel,
      communicativeFunction: communicativeFunction,
      languageVariant: languageVariant,
      imageUrl: imageUrl,
      createdAt: DateTime.now(),
      tags: tags,
    );
  }

  /// Generate unique ID
  static String _generateId() {
    return '${DateTime.now().millisecondsSinceEpoch}_${DateTime.now().microsecond}';
  }

  VocabularyModel copyWith({
    String? id,
    String? word,
    String? partOfSpeech,
    String? thaiTranslation,
    String? englishSentence,
    String? thaiSentence,
    String? cefrLevel,
    String? communicativeFunction,
    String? languageVariant,
    String? imageUrl,
    DateTime? createdAt,
    DateTime? updatedAt,
    List<String>? tags,
    bool? isFavorite,
  }) {
    return VocabularyModel(
      id: id ?? this.id,
      word: word ?? this.word,
      partOfSpeech: partOfSpeech ?? this.partOfSpeech,
      thaiTranslation: thaiTranslation ?? this.thaiTranslation,
      englishSentence: englishSentence ?? this.englishSentence,
      thaiSentence: thaiSentence ?? this.thaiSentence,
      cefrLevel: cefrLevel ?? this.cefrLevel,
      communicativeFunction: communicativeFunction ?? this.communicativeFunction,
      languageVariant: languageVariant ?? this.languageVariant,
      imageUrl: imageUrl ?? this.imageUrl,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      tags: tags ?? this.tags,
      isFavorite: isFavorite ?? this.isFavorite,
    );
  }

  /// Convert to JSON for storage/API
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'word': word,
      'partOfSpeech': partOfSpeech,
      'thaiTranslation': thaiTranslation,
      'englishSentence': englishSentence,
      'thaiSentence': thaiSentence,
      'cefrLevel': cefrLevel,
      'communicativeFunction': communicativeFunction,
      'languageVariant': languageVariant,
      'imageUrl': imageUrl,
      'createdAt': createdAt.toIso8601String(),
      'updatedAt': updatedAt?.toIso8601String(),
      'tags': tags,
      'isFavorite': isFavorite,
    };
  }

  /// Create from JSON
  factory VocabularyModel.fromJson(Map<String, dynamic> json) {
    return VocabularyModel(
      id: json['id'] as String,
      word: json['word'] as String,
      partOfSpeech: json['partOfSpeech'] as String,
      thaiTranslation: json['thaiTranslation'] as String,
      englishSentence: json['englishSentence'] as String,
      thaiSentence: json['thaiSentence'] as String,
      cefrLevel: json['cefrLevel'] as String,
      communicativeFunction: json['communicativeFunction'] as String,
      languageVariant: json['languageVariant'] as String,
      imageUrl: json['imageUrl'] as String,
      createdAt: DateTime.parse(json['createdAt'] as String),
      updatedAt: json['updatedAt'] != null
          ? DateTime.parse(json['updatedAt'] as String)
          : null,
      tags: (json['tags'] as List<dynamic>?)?.cast<String>() ?? [],
      isFavorite: json['isFavorite'] as bool? ?? false,
    );
  }

  @override
  List<Object?> get props => [
        id,
        word,
        cefrLevel,
      ];
}
