-- Create vocabularies table for storing user's learned vocabulary
-- Supports both local-first and cloud sync for registered users

-- Ensure the update_updated_at_column function exists (created in initial schema)
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = timezone('utc'::text, now());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS public.vocabularies (
  id TEXT PRIMARY KEY, -- Generated by client (timestamp_microsecond format)
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  word TEXT NOT NULL,
  part_of_speech TEXT NOT NULL,
  thai_translation TEXT NOT NULL,
  english_sentence TEXT NOT NULL,
  thai_sentence TEXT NOT NULL,
  cefr_level TEXT NOT NULL CHECK (cefr_level IN ('A1', 'A2', 'B1', 'B2')),
  communicative_function TEXT NOT NULL,
  language_variant TEXT NOT NULL CHECK (language_variant IN ('US', 'UK')),
  image_url TEXT NOT NULL,
  tags TEXT[] DEFAULT '{}',
  is_favorite BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create indexes for faster lookups
CREATE INDEX IF NOT EXISTS idx_vocabularies_user_id ON public.vocabularies(user_id);
CREATE INDEX IF NOT EXISTS idx_vocabularies_created_at ON public.vocabularies(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_vocabularies_word ON public.vocabularies(word);

-- Enable RLS
ALTER TABLE public.vocabularies ENABLE ROW LEVEL SECURITY;

-- Policy: Users can read their own vocabularies
CREATE POLICY "Users can view own vocabularies"
  ON public.vocabularies FOR SELECT
  USING (auth.uid() = user_id);

-- Policy: Users can insert their own vocabularies
CREATE POLICY "Users can insert own vocabularies"
  ON public.vocabularies FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Policy: Users can update their own vocabularies
CREATE POLICY "Users can update own vocabularies"
  ON public.vocabularies FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Policy: Users can delete their own vocabularies
CREATE POLICY "Users can delete own vocabularies"
  ON public.vocabularies FOR DELETE
  USING (auth.uid() = user_id);

-- Trigger to auto-update updated_at
DROP TRIGGER IF EXISTS update_vocabularies_updated_at ON public.vocabularies;
CREATE TRIGGER update_vocabularies_updated_at
  BEFORE UPDATE ON public.vocabularies
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- Function to get vocabulary count for a user
CREATE OR REPLACE FUNCTION public.get_user_vocabulary_count(user_uuid UUID)
RETURNS TABLE (
  total_count BIGINT,
  favorites_count BIGINT,
  today_count BIGINT
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    COUNT(*)::BIGINT as total_count,
    COUNT(*) FILTER (WHERE is_favorite = true)::BIGINT as favorites_count,
    COUNT(*) FILTER (WHERE DATE(created_at) = CURRENT_DATE)::BIGINT as today_count
  FROM public.vocabularies
  WHERE user_id = get_user_vocabulary_count.user_uuid;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
