// Mocks generated by Mockito 5.4.6 from annotations
// in starmory_app/test/unit/utc_16_17_18_sentence_generation_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:starmory_app/data/services/gemini_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeVocabularyExtractionResult_0 extends _i1.SmartFake
    implements _i2.VocabularyExtractionResult {
  _FakeVocabularyExtractionResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSentenceGenerationResult_1 extends _i1.SmartFake
    implements _i2.SentenceGenerationResult {
  _FakeSentenceGenerationResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GeminiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeminiService extends _i1.Mock implements _i2.GeminiService {
  MockGeminiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.VocabularyExtractionResult> extractVocabulary({
    required _i4.Uint8List? imageData,
    required String? level,
    required String? category,
    String? englishVariant = 'US',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#extractVocabulary, [], {
              #imageData: imageData,
              #level: level,
              #category: category,
              #englishVariant: englishVariant,
            }),
            returnValue: _i3.Future<_i2.VocabularyExtractionResult>.value(
              _FakeVocabularyExtractionResult_0(
                this,
                Invocation.method(#extractVocabulary, [], {
                  #imageData: imageData,
                  #level: level,
                  #category: category,
                  #englishVariant: englishVariant,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.VocabularyExtractionResult>);

  @override
  _i3.Future<_i2.SentenceGenerationResult> generateSentences({
    _i4.Uint8List? imageData,
    required List<String>? words,
    required String? level,
    required List<String>? tones,
    required String? category,
    required bool? combined,
    String? englishVariant = 'US',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateSentences, [], {
              #imageData: imageData,
              #words: words,
              #level: level,
              #tones: tones,
              #category: category,
              #combined: combined,
              #englishVariant: englishVariant,
            }),
            returnValue: _i3.Future<_i2.SentenceGenerationResult>.value(
              _FakeSentenceGenerationResult_1(
                this,
                Invocation.method(#generateSentences, [], {
                  #imageData: imageData,
                  #words: words,
                  #level: level,
                  #tones: tones,
                  #category: category,
                  #combined: combined,
                  #englishVariant: englishVariant,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.SentenceGenerationResult>);
}
